services:
  solara:
    build: .
    platform: linux/arm64
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=8080
    volumes:
      - ./downloads:/app/downloads
